<a href="https://colab.research.google.com/github/RamanPandey04/Datascience.assignment/blob/main/ds_2nd_question.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/Olympics.csv')

In [ ]:
# A

# Retrieve all records from the Olympics table

df

,id,name,sex,age,height,weight,team,noc,games,year,season,city,sport,event,medal
0,1,A Dijiang,M,24,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,32,Olav Augunson Aarnes,M,23,NaN,NaN,Norway,NOR,1912 Summer,1912,Summer,Stockholm,Athletics,Athletics Men's High Jump,NaN
96,33,Mika Lauri Aarnikka,M,24,187.0,76.0,Finland,FIN,1992 Summer,1992,Summer,Barcelona,Sailing,Sailing Men's Two Person Dinghy,NaN
97,33,Mika Lauri Aarnikka,M,28,187.0,76.0,Finland,FIN,1996 Summer,1996,Summer,Atlanta,Sailing,Sailing Men's Two Person Dinghy,NaN
98,34,Jamale (Djamel-) Aarrass (Ahrass-),M,30,187.0,76.0,France,FRA,2012 Summer,2012,Summer,London,Athletics,"""Athletics Men's 1,500 metres""",NaN
99,35,Dagfinn Sverre Aarskog,M,24,190.0,98.0,Norway,NOR,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN

In [ ]:
# B

# Retrieve only the Athlete names and the Medals they won

athlete_and_medal = print(df[['name', 'medal']])

                                  name medal
0                            A Dijiang   NaN
1                             A Lamusi   NaN
2                  Gunnar Nielsen Aaby   NaN
3                 Edgar Lindenau Aabye  Gold
4             Christine Jacoba Aaftink   NaN
..                                 ...   ...
95                Olav Augunson Aarnes   NaN
96                 Mika Lauri Aarnikka   NaN
97                 Mika Lauri Aarnikka   NaN
98  Jamale (Djamel-) Aarrass (Ahrass-)   NaN
99              Dagfinn Sverre Aarskog   NaN

[100 rows x 2 columns]

In [ ]:
# C

# Count the total number of athletes in the dataset.

total_athletes = print(df['name'].nunique())

35

In [ ]:
# D

# Find all records of athletes who won a Gold medal

gold_medals_df = print(df[df['medal'] == 'Gold'])

    id                       name sex  age  height  weight            team  \
3    4       Edgar Lindenau Aabye   M   34     NaN     NaN  Denmark/Sweden
42  17    Paavo Johannes Aaltonen   M   28   175.0    64.0         Finland
44  17    Paavo Johannes Aaltonen   M   28   175.0    64.0         Finland
48  17    Paavo Johannes Aaltonen   M   28   175.0    64.0         Finland
60  20         Kjetil Andr Aamodt   M   20   176.0    85.0          Norway
73  20         Kjetil Andr Aamodt   M   30   176.0    85.0          Norway
76  20         Kjetil Andr Aamodt   M   30   176.0    85.0          Norway
78  20         Kjetil Andr Aamodt   M   34   176.0    85.0          Norway
79  21  Ragnhild Margrethe Aamodt   F   27   163.0     NaN          Norway

    noc        games  year  season            city          sport  \
3   DEN  1900 Summer  1900  Summer           Paris     Tug-Of-War
42  FIN  1948 Summer  1948  Summer          London     Gymnastics
44  FIN  1948 Summer  1948  Summer          London     Gymnastics
48  FIN  1948 Summer  1948  Summer          London     Gymnastics
60  NOR  1992 Winter  1992  Winter     Albertville  Alpine Skiing
73  NOR  2002 Winter  2002  Winter  Salt Lake City  Alpine Skiing
76  NOR  2002 Winter  2002  Winter  Salt Lake City  Alpine Skiing
78  NOR  2006 Winter  2006  Winter          Torino  Alpine Skiing
79  NOR  2008 Summer  2008  Summer         Beijing       Handball

                               event medal
3        Tug-Of-War Men's Tug-Of-War  Gold
42  Gymnastics Men's Team All-Around  Gold
44      Gymnastics Men's Horse Vault  Gold
48  Gymnastics Men's Pommelled Horse  Gold
60       Alpine Skiing Men's Super G  Gold
73       Alpine Skiing Men's Super G  Gold
76      Alpine Skiing Men's Combined  Gold
78       Alpine Skiing Men's Super G  Gold
79         Handball Women's Handball  Gold

In [ ]:
# E

# List all athletes who won Silver, ordered by the Year they won it.

silver_medals_df = df[df['medal'] == 'Silver'].sort_values(by='year')
print(silver_medals_df[['name', 'year']])

                  name  year
86    Alf Lied Aanning  1920
63  Kjetil Andr Aamodt  1994
67  Kjetil Andr Aamodt  1994
92    Pepijn Aardewijn  1996

In [ ]:
# F

# Count how many Gold, Silver, and Bronze medals each country has won.

medals_by_country = print(df.groupby('noc')['medal'].value_counts().unstack(fill_value=0))

medal  Bronze  Gold  Silver
noc
DEN         0     1       0
FIN         5     3       0
NED         1     0       1
NOR         2     5       3

In [ ]:
# G

# Identify countries that have won more than 50 Gold medals.

gold_medal = df[df['medal'] == 'Gold']
gold_medal_counts = print(gold_medal.groupby('noc').size())

noc
DEN    1
FIN    3
NOR    5
dtype: int64

In [ ]:
# I

# Find the athlete who has won the most medals.

athlete_most_medals = print(df['name'].value_counts().idxmax())

Kjetil Andr Aamodt

In [ ]:
# J

# List all events that include the term 'Freestyle' in their name.

freestyle_events = print(df[df['event'].str.contains('Freestyle', case=False)]['event'].unique())

["Swimming Men's 400 metres Freestyle"]

In [ ]:
# K

# Find the top 3 athletes by the total number of medals won in each sport.

athlete_medal_counts = df.groupby(['sport', 'name'])['medal'].count().reset_index()
athlete_rankings = athlete_medal_counts.sort_values(by=['medal'], ascending=False).head(3)
athlete_rankings

            sport                     name  medal
0   Alpine Skiing       Kjetil Andr Aamodt      8
16     Gymnastics  Paavo Johannes Aaltonen      5
29       Swimming     Arvo Ossian Aaltonen      2

In [ ]:
# L

# List athletes who won more than one medal in a single Olympic year.

athlete_medal_counts = df.groupby(['year', 'name'])['medal'].count().reset_index()
multi_medal_winners = athlete_medal_counts[athlete_medal_counts['medal'] > 1].sort_values(by='medal',ascending=False)
multi_medal_winners

    year                     name  medal
9   1948  Paavo Johannes Aaltonen      4
30  1994       Kjetil Andr Aamodt      3
4   1920     Arvo Ossian Aaltonen      2
25  1992       Kjetil Andr Aamodt      2
44  2002       Kjetil Andr Aamodt      2

In [ ]:
# M

# Identify countries that have won gold medals in both Summer and Winter Olympics.

gold_medals_season = df[df['medal'] == 'Gold'].groupby(['noc', 'season']).size().unstack(fill_value=0)
countries_both_seasons = gold_medals_season[(gold_medals_season['Summer'] > 0) & (gold_medals_season['Winter'] > 0)].index.tolist()
print(countries_both_seasons)

['NOR']

In [ ]:
# N

# Show the year difference between the first and last medal won by each country.

first_last_medal_years = df.groupby('noc')['year'].agg(['min', 'max'])
first_last_medal_years['Year_Difference'] = first_last_medal_years['max'] - first_last_medal_years['min']
print(first_last_medal_years[['Year_Difference']])

     Year_Difference
noc
CHN               20
DEN               20
EST                0
FIN              102
FRA                0
NED               68
NOR               96
ROU                0
USA                2

In [ ]:
# S

# List countries that have won medals in more than 10 different sports.

countries_multiple_sports = df.groupby('noc')['sport'].nunique()
countries_more_than_10_sports = countries_multiple_sports[countries_multiple_sports > 10].index.tolist()
print(countries_more_than_10_sports)

[]